Update deconfigure scripts
Add comments to deconfigure scripts and during configuration make sure that
the deconfigure scripts are installed on the root file system so that the
deconfiguration can be done whether the cluster still exists or not.

Resolves #300

diff --git a/source/resources/playbooks/roles/ParallelClusterExternalLoginNodeDeconfigure/tasks/main.yml b/source/resources/playbooks/roles/ParallelClusterExternalLoginNodeDeconfigure/tasks/main.yml
--- a/source/resources/playbooks/roles/ParallelClusterExternalLoginNodeDeconfigure/tasks/main.yml
+++ b/source/resources/playbooks/roles/ParallelClusterExternalLoginNodeDeconfigure/tasks/main.yml
@@ -10,30 +10,32 @@
     dest: /etc/profile.d/slurm_{{ cluster_name }}_modulefiles.sh
     state: absent
 
-- name: Unmount /opt/slurm/{{ cluster_name }}
-  shell: |
-    set -ex
-
-    # Handle case where cluster was already deleted so the mountpoint is hung
-    if ! timeout 1s /opt/slurm/{{ cluster_name }}; then
-        echo "Mount point is hung. Source has already been deleted."
-        umount -lf /opt/slurm/{{ cluster_name }}
-    fi
-    if ! mountpoint /opt/slurm/{{ cluster_name }}; then
-        echo "/opt/slurm/{{ cluster_name }} already unmounted."
-        exit 0
-    fi
-    umount /opt/slurm/{{ cluster_name }} || lsof /opt/slurm/{{ cluster_name }}
-  register: umount_results
-
-- name: Show umount results
-  debug:
-    msg: |
-      umount_results: {{ umount_results }}
-
 - name: Remove /opt/slurm/{{ cluster_name }} from /etc/fstab
   mount:
     path: /opt/slurm/{{ cluster_name }}
     backup: true
     fstype: nfs
     state: absent
+
+- name: Unmount /opt/slurm/{{ cluster_name }}
+  shell: |
+    set -ex
+
+    # Handle case where cluster was already deleted so the mountpoint is hung.
+    # Do this first or other commands will hang too.
+    if ! timeout 1s /opt/slurm/{{ cluster_name }}; then
+        echo "Mount point is hung. Source has probably already been deleted."
+        umount -lf /opt/slurm/{{ cluster_name }}
+    fi
+    if ! [ -e /opt/slurm/{{ cluster_name }} ]; then
+        echo "/opt/slurm/{{ cluster_name }} doesn't exist."
+        exit 0
+    fi
+    if ! mountpoint /opt/slurm/{{ cluster_name }}; then
+        echo "/opt/slurm/{{ cluster_name }} already unmounted."
+        rmdir /opt/slurm/{{ cluster_name }}
+        exit 0
+    fi
+    echo "error: /opt/slurm/{{ cluster_name }} exists and is still mounted."
+    umount /opt/slurm/{{ cluster_name }} || lsof /opt/slurm/{{ cluster_name }}
+  register: umount_results
