Compile slurm for the os of the submitter
So that it can submit jobs to a cluster that uses a different OS.

Automate the configuration of the cluster manager and submitters in RES.

Fix errors in configuration scripts.

Add a parameter to the ParallelCluster custom resource that has a hash
of all of the config file contents so that the resource gets updated
whenever anything changes.
This current issue with this implementation is that the ParallelCluster
still doesn't change so even though the custom resource is updated,
the cluster doesn't because it's configuration is unchanged.

Fix a bug in configuring licenses.
After initial configuration the playbook was failing on subsequent updates.

Support custom munge key which must be specified in secretsmanager

Try to allow RES /home to be mounted, but currently causes a validation error.

Update EDA instance types to the latest and so that all memory sizes get built.

Restrict lambda function IAM roles and cleanup cfn_nag errors and warnings.

Resolves #177
Resolves #178
Resolves #180
Resolves #181

diff --git a/source/resources/playbooks/roles/ParallelClusterCreateUsersGroupsJsonDeconfigure/tasks/main.yml b/source/resources/playbooks/roles/ParallelClusterCreateUsersGroupsJsonDeconfigure/tasks/main.yml
--- a/source/resources/playbooks/roles/ParallelClusterCreateUsersGroupsJsonDeconfigure/tasks/main.yml
+++ b/source/resources/playbooks/roles/ParallelClusterCreateUsersGroupsJsonDeconfigure/tasks/main.yml
@@ -1,6 +1,50 @@
 ---
+# Tasks for ParallelClusterCreateUsersGroupsJsonDeconfigure
+
+- name: Show vars used in this playbook
+  debug:
+    msg: |
+      ClusterName:                {{ClusterName}}
 
 - name: Delete cron to refresh {{SlurmConfigDir}}/users_groups.json every hour
   file:
-    dest: /etc/cron.d/slurm_update_users_groups_json
+    dest: /etc/cron.d/slurm_{{ClusterName}}_update_users_groups_json
+    state: absent
+
+- name: Unmount /opt/slurm/{{ClusterName}}
+  shell: |
+    set -ex
+
+    # Handle case where cluster was already deleted so the mountpoint is hung
+    if ! timeout 1s /opt/slurm/{{ClusterName}}; then
+        echo "Mount point is hung. Source has already been deleted."
+        umount -lf /opt/slurm/{{ClusterName}}
+    fi
+    if ! mountpoint /opt/slurm/{{ClusterName}}; then
+        echo "/opt/slurm/{{ClusterName}} already unmounted."
+        exit 0
+    fi
+    umount -lf /opt/slurm/{{ClusterName}} || lsof /opt/slurm/{{ClusterName}}
+  register: umount_results
+
+- name: Show umount results
+  debug:
+    msg: |
+      umount_results: {{umount_results}}
+
+- name: Remove /opt/slurm/{{ClusterName}} from /etc/fstab and ignore errors
+  mount:
+    path: /opt/slurm/{{ClusterName}}
+    backup: true
+    fstype: nfs
+    state: absent
+  # For some reason umount is failing with device busy even though running out of /tmp.
+  # Retry it again without ignoring errors.
+  ignore_errors: true
+
+- name: Remove /opt/slurm/{{ClusterName}} from /etc/fstab
+  mount:
+    path: /opt/slurm/{{ClusterName}}
+    backup: true
+    fstype: nfs
     state: absent
